# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit Abhi-1U.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
data("AirPassengers")


## -----------------------------------------------------------------------------
acf(
    log(AirPassengers)
)


## ---- eval = knitr::is_html_output(), layout = "l-body-outset"----------------
#> (fit <- arima(
#>     log(AirPassengers),
#>     c(0,1,1),
#>     seasonal=list(order=c(0,1,1),
#>                   period=12)
#>     )
#> )


## ---- eval = knitr::is_latex_output(), layout = "l-body-outset"---------------
(fit <- arima(
    log(AirPassengers),
    c(0,1,1),
    seasonal=list(order=c(0,1,1),
                  period=12)
    )
)

